services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
      - "10087:10087"
    volumes:
      - /home/pedro/TEG/hamaca/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:10.0.0-ubuntu
    ports:
      - "3000:3000"
    volumes:
      -  grafana-storage:/var/lib/grafana
    links:
      - "prometheus"
    user: "472"
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"



volumes:
   grafana-storage: {}
