# Generated by Django 2.0.6 on 2019-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttdef',
            old_name='valor',
            new_name='payload',
        ),
        migrations.RemoveField(
            model_name='mqttdef',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='mqttdef',
            name='variable',
        ),
        migrations.AddField(
            model_name='mqttdef',
            name='cant_mensajes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mqttdef',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mqttdef',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
