################################################################################
# Hamaca Stack o Compose
################################################################################
# docker stack deploy para TEG con los componentes de influxdb, grafana, nodered
################################################################################

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influx-storage:/var/lib/influxdb
  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #     - "10087:10087"
  #   volumes:
  #     - /home/pedro/TEG/hamaca/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:10.0.0-ubuntu
    restart: always
    ports:
      - "3000:3000"
    volumes:
      -  grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    # links:
    #   - "prometheus"
    user: "472"
    depends_on:
      - influxdb
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered-storage:/data

volumes:
  grafana-storage:
    external: true
  influx-storage:
    external: true
  nodered-storage:
    external: true
